# -*-coding:utf-8-*-
import datetime

data = {'id': '14686248208',
        'type': 'PullRequestEvent',
        'actor': {'id': 22910552, 'login': 'TGElder', 'display_login': 'TGElder'},
        'repo': {'id': 290008803, 'name': 'TGElder/rust'},
        'payload': {'action': 'opened',
                    'number': 73,
                    'pull_request': {'id': 547631964,
                                     'node_id': 'MDExOlB1bGxSZXF1ZXN0NTQ3NjMxOTY0',
                                     'number': 73, 'state': 'open',
                                     'title': 'refactor: merging system and configuration modules',
                                     'user': {'login': 'TGElder',
                                              'id': 22910552,
                                              'node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                                              'type': 'User'},
                                     'body': '',
                                     'created_at': '2021-01-01T14:00:00Z',
                                     'updated_at': '2021-01-01T14:00:00Z',
                                     'closed_at': '2021-01-01T14:00:00Z',
                                     'merged_at': '2021-01-01T14:00:00Z',
                                     'merge_commit_sha': '',
                                     'head': {
                                         'label': 'TGElder:system-refactor',
                                         'ref': 'system-refactor',
                                         'sha': '4b45e311608d0639250ed25e173d568169bc11be',
                                         'user': {'login': 'TGElder',
                                                  'id': 22910552,
                                                  'node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                                                  'type': 'User'},
                                         'repo': {'id': 290008803,
                                                  'node_id': 'MDEwOlJlcG9zaXRvcnkyOTAwMDg4MDM=',
                                                  'name': 'rust',
                                                  'full_name': 'TGElder/rust',
                                                  'private': False,
                                                  'owner': {
                                                      'login': 'TGElder',
                                                      'id': 22910552,
                                                      'node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                                                      'type': 'User'},
                                                  'description': 'Monorepo for Rust projects',
                                                  'fork': False,
                                                  'created_at': '2020-08-24T18:34:25Z',
                                                  'updated_at': '2020-12-16T20:40:41Z',
                                                  'pushed_at': '2020-12-31T19:37:40Z',
                                                  'language': 'Rust',
                                                  'default_branch': 'develop'}},
                                     'base': {
                                         'label': 'TGElder:game-refactor',
                                         'ref': 'game-refactor',
                                         'sha': '965eaceb5ffd65fcd6a5dadeeb9bfc913ed91cbc',
                                         'user': {'login': 'TGElder',
                                                  'id': 22910552,
                                                  'node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                                                  'type': 'User'},
                                         'repo': {'id': 290008803,
                                                  'node_id': 'MDEwOlJlcG9zaXRvcnkyOTAwMDg4MDM=',
                                                  'name': 'rust',
                                                  'full_name': 'TGElder/rust',
                                                  'private': False,
                                                  'owner': {
                                                      'login': 'TGElder',
                                                      'id': 22910552,
                                                      'node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                                                      'type': 'User'},
                                                  'description': 'Monorepo for Rust projects',
                                                  'fork': False,
                                                  'created_at': '2020-08-24T18:34:25Z',
                                                  'updated_at': '2020-12-16T20:40:41Z',
                                                  'pushed_at': '2020-12-31T19:37:40Z',
                                                  'language': 'Rust',
                                                  'default_branch': 'develop'}},
                                     'author_association': 'OWNER',
                                     'merged': False,
                                     'mergeable_state': 'unknown',
                                     'merged_by': {
                                         'login': 'TGElder',
                                         'id': 22910552,
                                         'node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                                         'type': 'User'}}},
        'created_at': '2021-01-01T14:00:01Z'}


cleaned_data = {'id': data['id'],
                'type': data['type'],
                'created_at': datetime.datetime.strptime(data['created_at'], '%Y-%m-%dT%H:%M:%SZ'),
                'actor__id': data['actor']['id'],
                'actor__login': data['actor']['login'],
                'actor__display_login': data['actor']['display_login'],
                'repo__id': data['repo']['id'],
                'repo__name': data['repo']['name'],
                'payload__action': data['payload']['action'],
                'payload__number': data['payload']['number'],
                'payload__pull_request__id': data['payload']['pull_request']['id'],
                'payload__pull_request__node_id': data['payload']['pull_request']['node_id'],
                'payload__pull_request__number': data['payload']['pull_request']['number'],
                'payload__pull_request__state': data['payload']['pull_request']['state'],
                'payload__pull_request__title': data['payload']['pull_request']['title'],
                'payload__pull_request__user__login': data['payload']['pull_request']['user']['login'],
                'payload__pull_request__user__id': data['payload']['pull_request']['user']['id'],
                'payload__pull_request__user__node_id': data['payload']['pull_request']['user']['node_id'],
                'payload__pull_request__user__type': data['payload']['pull_request']['user']['type'],
                'payload__pull_request__created_at': datetime.datetime.strptime(data['payload']['pull_request']['created_at'], '%Y-%m-%dT%H:%M:%SZ'),
                'payload__pull_request__updated_at': datetime.datetime.strptime(data['payload']['pull_request']['updated_at'], '%Y-%m-%dT%H:%M:%SZ'),
                'payload__pull_request__closed_at': datetime.datetime.strptime(data['payload']['pull_request']['closed_at'], '%Y-%m-%dT%H:%M:%SZ'),
                'payload__pull_request__merged_at': datetime.datetime.strptime(data['payload']['pull_request']['merged_at'], '%Y-%m-%dT%H:%M:%SZ'),
                'payload__pull_request__head__label': data['payload']['pull_request']['head']['label'],
                'payload__pull_request__head__ref': data['payload']['pull_request']['head']['ref'],
                'payload__pull_request__head__sha': data['payload']['pull_request']['head']['sha'],
                'payload__pull_request__head__user__login': data['payload']['pull_request']['head']['user']['login'],
                'payload__pull_request__head__user__id': data['payload']['pull_request']['head']['user']['id'],
                'payload__pull_request__head__user__node_id': data['payload']['pull_request']['head']['user']['node_id'],
                'payload__pull_request__head__user__type': 'User',
                'payload__pull_request__head__repo__id': 290008803,
                'payload__pull_request__head__repo__node_id': 'MDEwOlJlcG9zaXRvcnkyOTAwMDg4MDM=',
                'payload__pull_request__head__repo__name': 'rust',
                'payload__pull_request__head__repo__full_name': 'TGElder/rust',
                'payload__pull_request__head__repo__owner__login': 'TGElder',
                'payload__pull_request__head__repo__owner__id': 22910552,
                'payload__pull_request__head__repo__owner__node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                'payload__pull_request__head__repo__owner__type': 'User',
                'payload__pull_request__head__repo__description': 'Monorepo for Rust projects',
                'payload__pull_request__head__repo__created_at': '2020-08-24T18:34:25Z',
                'payload__pull_request__head__repo__updated_at': '2020-12-16T20:40:41Z',
                'payload__pull_request__head__repo__pushed_at': '2020-12-31T19:37:40Z',
                'payload__pull_request__head__repo__language': 'Rust',
                'payload__pull_request__head__repo__default_branch': 'develop',
                'payload__pull_request__base__label': 'TGElder:game-refactor',
                'payload__pull_request__base__ref': 'game-refactor',
                'payload__pull_request__base__sha': '965eaceb5ffd65fcd6a5dadeeb9bfc913ed91cbc',
                'payload__pull_request__base__user__login': 'TGElder',
                'payload__pull_request__base__user__id': 22910552,
                'payload__pull_request__base__user__node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                'payload__pull_request__base__user__type': 'User', 'payload__pull_request__base__repo__id': 290008803,
                'payload__pull_request__base__repo__node_id': 'MDEwOlJlcG9zaXRvcnkyOTAwMDg4MDM=',
                'payload__pull_request__base__repo__name': 'rust',
                'payload__pull_request__base__repo__full_name': 'TGElder/rust',
                'payload__pull_request__base__repo__owner__login': 'TGElder',
                'payload__pull_request__base__repo__owner__id': 22910552,
                'payload__pull_request__base__repo__owner__node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                'payload__pull_request__base__repo__owner__type': 'User',
                'payload__pull_request__base__repo__description': 'Monorepo for Rust projects',
                'payload__pull_request__base__repo__created_at': '2020-08-24T18:34:25Z',
                'payload__pull_request__base__repo__updated_at': '2020-12-16T20:40:41Z',
                'payload__pull_request__base__repo__pushed_at': '2020-12-31T19:37:40Z',
                'payload__pull_request__base__repo__language': 'Rust',
                'payload__pull_request__base__repo__default_branch': 'develop',
                'payload__pull_request__author_association': 'OWNER',
                'payload__pull_request__mergeable_state': 'unknown',
                'payload__pull_request__merged_by__login': 'TGElder', 'payload__pull_request__merged_by__id': 22910552,
                'payload__pull_request__merged_by__node_id': 'MDQ6VXNlcjIyOTEwNTUy',
                'payload__pull_request__merged_by__type': 'User'}
