# -*-coding:utf-8-*-
import datetime

data = {'id': '14686248187', 'type': 'ForkEvent',
        'actor': {'id': 69684119, 'login': 'SiddharthPanwar', 'display_login': 'SiddharthPanwar'},
        'repo': {'id': 235751381, 'name': 'whitehatjr/BarCodeScanner'},
        'payload': {
            'forkee': {'id': 325989556,
                       'node_id': 'MDEwOlJlcG9zaXRvcnkzMjU5ODk1NTY=',
                       'name': 'BarCodeScanner',
                       'full_name': 'SiddharthPanwar/BarCodeScanner',
                       'private': False,
                       'owner': {'login': 'SiddharthPanwar',
                                 'id': 69684119,
                                 'node_id': 'MDQ6VXNlcjY5Njg0MTE5',
                                 'type': 'User',
                                 'site_admin': False
                                 },
                       'description': 'BarCode scanning in WiLy',
                       'fork': True,
                       'created_at': '2021-01-01T14:00:00Z',
                       'updated_at': '2020-09-08T16:20:05Z',
                       'pushed_at': '2020-09-05T04:35:46Z',
                       'size': 238,
                       'stargazers_count': 0,
                       'watchers_count': 0,
                       'language': None,
                       'has_issues': False,
                       'has_projects': True,
                       'has_downloads': True,
                       'has_wiki': True,
                       'has_pages': False,
                       'forks_count': 0,
                       'archived': False,
                       'disabled': False,
                       'open_issues_count': 0,
                       'license': None,
                       'forks': 0,
                       'open_issues': 0,
                       'watchers': 0,
                       'default_branch': 'main',
                       'public': True}},
        'public': True,
        'created_at': '2021-01-01T14:00:00Z'}

cleaned_data = {'id': data['id'],
                'type': data['type'],
                'public': 1,
                'created_at': datetime.datetime.strptime(data['created_at'], '%Y-%m-%dT%H:%M:%SZ'),
                'actor__id': data['actor']['id'],
                'actor__login': data['actor']['login'],
                'actor__display_login': data['actor']['display_login'],
                'repo__id': data['repo']['id'],
                'repo__name': data['repo']['name'],
                'payload__forkee__id': data['payload']['forkee']['id'],
                'payload__forkee__node_id': data['payload']['forkee']['node_id'],
                'payload__forkee__name': data['payload']['forkee']['node_id'],
                'payload__forkee__full_name': data['payload']['forkee']['node_id'],
                'payload__forkee__owner__login': data['payload']['forkee']['node_id'],
                'payload__forkee__owner__id': data['payload']['forkee']['node_id'],
                'payload__forkee__owner__node_id': data['payload']['forkee']['node_id'],
                'payload__forkee__owner__type': data['payload']['forkee']['node_id'],
                'payload__forkee__description': data['payload']['forkee']['node_id'],
                'payload__forkee__fork': data['payload']['forkee']['node_id'],
                'payload__forkee__created_at': data['payload']['forkee']['node_id'],
                'payload__forkee__updated_at': data['payload']['forkee']['node_id'],
                'payload__forkee__pushed_at': data['payload']['forkee']['node_id'],
                'payload__forkee__size': 238,
                'payload__forkee__has_projects': 1,
                'payload__forkee__has_downloads': 1,
                'payload__forkee__has_wiki': 1,
                'payload__forkee__default_branch': 'main', 'payload__forkee__public': 1}

cleaned_data_v2 = {'id': data['id'],
                    'type': data['type'],
                    'public': 1,
                    'created_at': datetime.datetime.strptime(data['created_at'], '%Y-%m-%dT%H:%M:%SZ'),
                    'actor__id': data['actor']['id'],
                    'actor__login': data['actor']['id'],
                    'actor__display_login': data['actor']['display_login'],
                    'repo__id': data['repo']['id'],
                    'repo__name': data['repo']['name'],
                    'payload__forkee__id': data['payload']['forkee']['id'],
                    'payload__forkee__node_id': data['payload']['forkee']['node_id'],
                    'payload__forkee__name': data['payload']['forkee']['node_id'],
                    'payload__forkee__full_name': data['payload']['forkee']['node_id'],
                   'payload__forkee__owner__login': data['payload']['forkee']['node_id'],
                   'payload__forkee__owner__id': data['payload']['forkee']['node_id'],
                   'payload__forkee__owner__node_id': data['payload']['forkee']['node_id'],
                   'payload__forkee__owner__type': data['payload']['forkee']['node_id'],
                   'payload__forkee__owner__site_admin': 1,
                   'payload__forkee__description': data['payload']['forkee']['node_id'],
                   'payload__forkee__created_at': datetime.datetime.strptime(data['payload']['forkee']['created_at'], '%Y-%m-%dT%H:%M:%SZ'),
                   'payload__forkee__updated_at': datetime.datetime.strptime(data['payload']['forkee']['updated_at'], '%Y-%m-%dT%H:%M:%SZ'),
                   'payload__forkee__pushed_at': datetime.datetime.strptime(data['payload']['forkee']['pushed_at'], '%Y-%m-%dT%H:%M:%SZ'),
                   'payload__forkee__default_branch': data['payload']['forkee']['branch'],
                   }
